# Generated by Django 4.2 on 2023-04-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('address', models.TextField()),
                ('age', models.IntegerField()),
                ('dob', models.DateField()),
                ('sscSchoolName', models.CharField(max_length=250)),
                ('hscSchoolName', models.CharField(max_length=250)),
                ('graduationCollegeName', models.CharField(max_length=250)),
                ('sscPercentage', models.IntegerField()),
                ('hscPercentage', models.IntegerField()),
                ('graduationPercentage', models.IntegerField()),
                ('experience', models.TextField()),
                ('carrer_objective', models.TextField()),
                ('skills', models.TextField()),
                ('contacts', models.TextField()),
            ],
        ),
    ]
