# Generated by Django 4.2 on 2023-04-27 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_resumemodel_resume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='carrer_objective',
            new_name='career_objective',
        ),
    ]
